### ISSUE TITLE
`preserve_newline` and `max_preserve_newline` options not doign anything?

### ISSUE THREAD

**Issue by jakerella** [jonschlinkert/grunt-prettify#13]
I'm using this task in my build process and I want to keep blank lines around code, but only 1 extra blank line. I can turn off condensing entirely with the `condense` option, but is seems like setting `preserve_newline: true, max_preserve_newline: 2` would get me an allowable extra blank line, but not two blank lines. But it doesn't work. In fact, changing those options doesn't seem to do anything.

I look at the source in `/tasks/prettify.js` and I don't see those two options being used anywhere. Am I missing something?

**Comment by jonschlinkert** [comment]
No, you're not missing anything. This task just exposes the options from js-beautify, this is something that I had trouble with as well. e.g. the options you're having problems with just don't seem to work. I believe there was an issue on js-beautify about this.

I'm closing since this is something that should really be addressed on js-beautify. However, if you find a workaround or if it does indeed turn out that the issue needs to be addressed here, please feel free to reopen.

**Comment by jakerella** [comment]
Hmm... Interesting. Looks like the `beautify-html.js` file does use this... argh.
